# SPDX-License-Identifier: GPL-2.0-only
# Minimal DKMS configuration for the MVGAL kernel module.

PACKAGE_NAME="mvgal"
PACKAGE_VERSION="0.2.2"
BUILT_MODULE_NAME[0]="mvgal"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make -C ${kernel_source_dir}/kernel"
CLEAN="make -C ${kernel_source_dir}/kernel clean"
